### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by zeteticl** [TiagoDanin/Telegraf-GetChatMembers#1]
when i add
const telegrafGetChatMembers = require('telegraf-getchatmembers')

		TGclient.use(telegrafGetChatMembers)

and the bot in channels as admin

it just got error
" TypeError: Cannot read property 'id' of undefined"
XXXXnode_modules\telegraf-getchatmembers\index.js:22:50)
at process._tickCallback (internal/process/next_tick.js:68:7)
telegraf.js:27
Failed to process updates.
telegraf.js:174
TypeError: Cannot read property 'id' of undefined

**Comment by TiagoDanin** [comment]
Done. sorry delay 
https://github.com/TiagoDanin/Telegraf-GetChatMembers/releases/tag/v1.0.1
